# Generated by Django 2.1.5 on 2019-02-01 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountriesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
                ('number_of_drivers', models.IntegerField()),
                ('events_finished', models.IntegerField()),
                ('average_finish_place', models.FloatField()),
                ('first_places', models.IntegerField()),
                ('top_3', models.IntegerField()),
                ('top_10', models.IntegerField()),
                ('top_100', models.IntegerField()),
                ('percentile_1st_place', models.FloatField()),
                ('percentile_top_3', models.FloatField()),
                ('percentile_top_10', models.FloatField()),
                ('percentile_top_100', models.FloatField()),
                ('total_driving_time_seconds', models.FloatField()),
                ('total_driving_time_string', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['country_name'],
            },
        ),
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_category', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('event_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('stage', models.CharField(max_length=50)),
                ('time_of_the_day', models.CharField(max_length=50)),
                ('weather', models.CharField(max_length=50)),
                ('total_drivers', models.IntegerField()),
            ],
            options={
                'ordering': ['event_category', 'date'],
            },
        ),
        migrations.CreateModel(
            name='LastDatabaseUpdateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_database_update_time', models.CharField(max_length=100)),
                ('days_database_active', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('country_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('vehicle', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('time_seconds', models.FloatField()),
                ('diff_1st', models.CharField(max_length=50)),
                ('player_id', models.IntegerField()),
                ('event_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapping.EventInfo')),
            ],
            options={
                'ordering': ['-position'],
            },
        ),
        migrations.CreateModel(
            name='NoCountryNameCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_country_name', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayersInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_from', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('player_id', models.IntegerField()),
                ('events_finished', models.IntegerField()),
                ('average_finish_place', models.FloatField()),
                ('first_places', models.IntegerField()),
                ('top_3', models.IntegerField()),
                ('top_10', models.IntegerField()),
                ('top_100', models.IntegerField()),
                ('percentile_1st_place', models.FloatField()),
                ('percentile_top_3', models.FloatField()),
                ('percentile_top_10', models.FloatField()),
                ('percentile_top_100', models.FloatField()),
                ('total_driving_time_seconds', models.FloatField()),
                ('total_driving_time_string', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['player_id'],
            },
        ),
        migrations.CreateModel(
            name='SiteUpdateStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_status', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TotalQualifiedCountries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualified_countries', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalQualifiedDrivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualified_drivers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalUniqueDrivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id_list_len', models.IntegerField()),
            ],
        ),
    ]
