# Generated by Django 2.1 on 2018-08-20 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_category', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('event_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('stage', models.CharField(max_length=50)),
                ('time_of_the_day', models.CharField(max_length=50)),
                ('weather', models.CharField(max_length=50)),
                ('total_drivers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('country_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('vehicle', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('time_seconds', models.FloatField()),
                ('diff_1st', models.CharField(max_length=50)),
                ('player_id', models.IntegerField()),
                ('event_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapping.EventInfo')),
            ],
        ),
    ]
