# Generated by Django 2.1.5 on 2019-03-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0002_auto_20190320_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nocountrynamecheck',
            name='no_country_name',
            field=models.CharField(max_length=100),
        ),
    ]
