# Generated by Django 2.1 on 2018-09-18 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0003_nocountrynamecheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_appearance_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayersIDList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('country_name', models.CharField(max_length=100)),
                ('events_finished', models.IntegerField()),
                ('total_driving_time', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='totaluniquedrivers',
            old_name='leaderboard',
            new_name='player_id_list_len',
        ),
        migrations.AddField(
            model_name='playernames',
            name='players_id_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapping.PlayersIDList'),
        ),
    ]
