# Generated by Django 2.1.5 on 2019-03-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0003_auto_20190320_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueIPConnections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=500)),
            ],
        ),
    ]
