# Generated by Django 2.1 on 2018-09-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0004_auto_20180918_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playernames',
            name='players_id_list',
        ),
        migrations.RemoveField(
            model_name='playersidlist',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='playersidlist',
            name='events_finished',
        ),
        migrations.RemoveField(
            model_name='playersidlist',
            name='total_driving_time',
        ),
        migrations.DeleteModel(
            name='PlayerNames',
        ),
    ]
