# Generated by Django 2.1 on 2018-09-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0005_auto_20180918_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboard',
            old_name='player_id',
            new_name='player_id_1',
        ),
        migrations.RenameField(
            model_name='playersidlist',
            old_name='player_id',
            new_name='player_id_2',
        ),
    ]
