# Generated by Django 2.1 on 2018-09-21 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0006_auto_20180921_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboard',
            old_name='player_id_1',
            new_name='player_id',
        ),
        migrations.RenameField(
            model_name='playersidlist',
            old_name='player_id_2',
            new_name='player_id',
        ),
    ]
