# Generated by Django 2.1 on 2018-09-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0007_auto_20180921_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayersInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('country_from', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('events_finished', models.IntegerField()),
                ('first_places', models.IntegerField()),
                ('top_3', models.IntegerField()),
                ('top_10', models.IntegerField()),
                ('top_100', models.IntegerField()),
                ('total_driving_time', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='PlayersIDList',
        ),
    ]
