# Generated by Django 2.1 on 2018-10-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0017_auto_20180930_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounriesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counrie_name', models.CharField(max_length=50)),
                ('events_finished', models.IntegerField()),
                ('average_finish_place', models.FloatField()),
                ('first_places', models.IntegerField()),
                ('top_3', models.IntegerField()),
                ('top_10', models.IntegerField()),
                ('top_100', models.IntegerField()),
                ('total_driving_time', models.FloatField()),
            ],
        ),
    ]
