# Generated by Django 2.1 on 2018-10-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0018_counriesinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counriesinfo',
            old_name='counrie_name',
            new_name='country_name',
        ),
    ]
