# Generated by Django 2.1 on 2018-10-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0021_auto_20181004_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playersinfo',
            options={'ordering': ['player_id']},
        ),
    ]
