# Generated by Django 2.1 on 2018-11-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0023_auto_20181021_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playersinfo',
            old_name='total_driving_time',
            new_name='total_driving_time_seconds',
        ),
        migrations.AddField(
            model_name='playersinfo',
            name='total_driving_time_string',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
    ]
