# Generated by Django 2.1 on 2018-11-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0025_auto_20181102_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='countriesinfo',
            name='total_driving_time2',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
