# Generated by Django 2.1 on 2018-11-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0026_countriesinfo_total_driving_time2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countriesinfo',
            name='total_driving_time2',
        ),
    ]
