# Generated by Django 2.1 on 2018-11-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0031_remove_playersinfo_total_driving_time_seconds2'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastdatabaseupdatetime',
            name='days_database_active',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
