# Generated by Django 2.1 on 2018-12-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0033_siteupdatestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='countriesinfo',
            name='percentile_1st_place',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countriesinfo',
            name='percentile_top_10',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countriesinfo',
            name='percentile_top_100',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countriesinfo',
            name='percentile_top_3',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playersinfo',
            name='percentile_1st_place',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playersinfo',
            name='percentile_top_10',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playersinfo',
            name='percentile_top_100',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playersinfo',
            name='percentile_top_3',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteupdatestatus',
            name='update_status',
            field=models.CharField(max_length=500),
        ),
    ]
